const ADD_PERSON_FAVORITES = 'ADD_PERSON_FAVORITES';
const DELETE_PERSON_FAVORITES = 'DELETE_PERSON_FAVORITES';
const ADD_PERSON = 'ADD_PERSON';

const REGISTRA_USUARIO = 'REGISTRA_USUARIO';
const LOGEA_USUARIO = 'LOGEA_USUARIO';
const DESLOGEAR = 'DESLOGEAR';
const SET_LOADING = 'SET_LOADING';
const SET_ERROR = 'SET_ERROR';
const SET_SUCCESS = 'SET_SUCCESS';

export { ADD_PERSON_FAVORITES, DELETE_PERSON_FAVORITES, ADD_PERSON, REGISTRA_USUARIO, LOGEA_USUARIO, DESLOGEAR, SET_LOADING, SET_ERROR, SET_SUCCESS };
